import{i as a,S as c}from"./assets/vendor-B2mb6eXk.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const l="48551671-8e0bd0e05b8a9090cbea8e4d9";function d(i){const s=`https://pixabay.com/api/?key=${l}&q=${encodeURIComponent(i)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(s).then(t=>t.json()).then(t=>t.hits).catch(t=>{console.error("REQUEST ERROR",t),iziToast.error({title:"Error",message:"Failed to fetch images. Please try again!",position:"topRight"})})}function m(i){const s=document.getElementById("gallery");if(s.innerHTML="",i.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}i.forEach(t=>{const o=document.createElement("div");o.classList.add("image-card");const e=document.createElement("a");e.href=t.largeImageURL,e.classList.add("image-link");const r=document.createElement("img");r.src=t.webformatURL,r.alt=t.tags,r.classList.add("image");const n=document.createElement("div");n.classList.add("image-info"),n.innerHTML=`
        <p class="image-likes text">Likes</p>
        <p class="image-views text">Views</p>
        <p class="image-downloads text">Downloads</p>
        <p class="image-comments text">Comments</p>
        <p class="number">${t.likes}</p>
        <p class="number">${t.views}</p>
        <p class="number">${t.downloads}</p>
        <p class="number">${t.comments}</p>
        `,e.appendChild(r),o.appendChild(e),o.appendChild(n),s.appendChild(o)})}document.getElementById("form").addEventListener("submit",function(i){i.preventDefault();const s=document.getElementById("input").value.trim();if(!s){a.error({title:"Error",message:"Please enter search request!",position:"topRight"});return}const t=document.querySelector(".loader");t.style.visibility="visible",d(s).then(function(o){m(o),new c(".image-link",{captionsData:"alt",captionDelay:500}).refresh()}).catch(o=>{console.error("RENDER ERROR",o),a.error({title:"Error",message:"Failed to load images. Please try again!",position:"topRight"})}).finally(()=>{t.style.visibility="hidden"})});
//# sourceMappingURL=index.js.map
